[workspace]
resolver = "2"
members = [
    "crates/domain",
    "crates/db",
    "crates/core-loader-desktop",
    "crates/emu-session",
    "crates/video-surface",
    "crates/audio-desktop",
    "crates/library-scan",
    "crates/input-desktop",
    "crates/shader-slang",
    "apps/desktop/src-tauri",
    # adapters de plataforma são adicionados aqui conforme forem criados:
    # "crates/core-loader-mobile",
    # "apps/mobile/src-tauri",
]

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1"
async-trait = "0.1"
