/**
 * Linguagem visual do "modo Xbox" (ver docs/design/xbox-mode-reference.md e
 * docs/design/fluent2.md) em **Griffel** (`makeStyles` + `tokens` do Fluent 2),
 * substituindo o antigo `xbox.css`.
 *
 * Cores/raio/rail specifics do "console look" (quase-preto + verde Xbox) ficam
 * em `brand` — a ramp do Fluent 2 é clara demais pra tela cheia. Texto, stroke,
 * spacing, motion e tipografia usam `tokens`.
 *
 * CUIDADO (WebKitGTK, ver src-tauri/src/main.rs): nada de `backdrop-filter`
 * nem `radial-gradient` multicamada em elemento `position: fixed`.
 */
import { makeStyles, tokens } from '@fluentui/react-components'

const brand = {
  bg: '#0b0b0d',
  bgElev: '#17171b',
  bgElev2: '#1f1f24',
  appBg: 'linear-gradient(180deg, #14141b 0%, #0b0b0d 42%)',
  accent: '#6cc04a',
  accentSoft: 'rgba(108, 192, 74, 0.16)',
  radius: '12px',
  radiusLg: '16px',
  railW: '64px',
}

const fastTransition = {
  transitionDuration: tokens.durationFaster,
  transitionTimingFunction: tokens.curveEasyEase,
}

/** Casca: app / rail / topbar / área de rolagem + anel de foco global. */
export const useShellStyles = makeStyles({
  app: {
    position: 'fixed',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    backgroundImage: brand.appBg,
    color: tokens.colorNeutralForeground1,
    fontFamily: tokens.fontFamilyBase,
    display: 'grid',
    gridTemplateColumns: `${brand.railW} 1fr`,
    overflowX: 'hidden',
    overflowY: 'hidden',
    // brilho de canto (1 camada só — multicamada quebra o WebKitGTK)
    '::before': {
      content: '""',
      position: 'absolute',
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
      backgroundImage: `radial-gradient(760px 420px at 8% -8%, ${brand.accentSoft}, transparent 70%)`,
      pointerEvents: 'none',
    },
    // Anel de foco forte pra navegação por controle. `:focus` (não só
    // `:focus-visible`): o pulso do gamepad vem de um evento Tauri, sem
    // keydown, então o WebKitGTK não marca `:focus-visible` no `.focus()`
    // programático — e o usuário não via onde estava o foco.
    '& a:focus, & button:focus, & input:focus, & [tabindex]:focus': {
      outlineWidth: '3px',
      outlineStyle: 'solid',
      outlineColor: tokens.colorNeutralForeground1,
      outlineOffset: '2px',
      borderRadius: brand.radius,
    },
  },

  rail: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    rowGap: '4px',
    paddingTop: '14px',
    paddingBottom: '14px',
    borderRight: `1px solid ${tokens.colorNeutralStroke2}`,
    backgroundColor: 'rgba(0, 0, 0, 0.28)',
  },
  railSpacer: { flexGrow: 1 },
  railSep: {
    width: '26px',
    height: '1px',
    backgroundColor: tokens.colorNeutralStroke2,
    marginTop: '6px',
    marginBottom: '6px',
  },
  railItem: {
    position: 'relative',
    width: '44px',
    height: '44px',
    display: 'grid',
    alignItems: 'center',
    justifyItems: 'center',
    borderRadius: brand.radius,
    color: tokens.colorNeutralForeground3,
    textDecorationLine: 'none',
    fontSize: '22px',
    border: 'none',
    backgroundColor: 'transparent',
    cursor: 'pointer',
    transitionProperty: 'background-color, color',
    ...fastTransition,
    ':hover': {
      backgroundColor: brand.bgElev,
      color: tokens.colorNeutralForeground1,
    },
    '&[aria-current="page"]': { color: tokens.colorNeutralForeground1 },
    // indicador ativo: barra vertical fina na borda esquerda
    '&[aria-current="page"]::before': {
      content: '""',
      position: 'absolute',
      left: '-10px',
      top: '50%',
      transform: 'translateY(-50%)',
      width: '3px',
      height: '22px',
      borderRadius: '3px',
      backgroundColor: tokens.colorNeutralForeground1,
    },
  },
  railQuit: {
    ':hover': {
      backgroundColor: 'rgba(220, 60, 60, 0.18)',
      color: '#ff8a8a',
    },
  },
  railBrand: {
    width: '38px',
    height: '38px',
    borderRadius: '50%',
    marginBottom: '8px',
    objectFit: 'cover',
    backgroundColor: brand.accent,
    display: 'grid',
    alignItems: 'center',
    justifyItems: 'center',
    fontWeight: 800,
    color: brand.bg,
  },

  main: { display: 'flex', flexDirection: 'column', minHeight: 0 },
  topbar: {
    position: 'relative',
    display: 'flex',
    alignItems: 'center',
    columnGap: '14px',
    paddingTop: '14px',
    paddingBottom: '14px',
    paddingLeft: '32px',
    paddingRight: '32px',
    flexShrink: 0,
    backgroundColor: 'transparent',
  },
  topbarSpacer: { flexGrow: 1 },
  iconBtn: {
    width: '38px',
    height: '38px',
    display: 'grid',
    alignItems: 'center',
    justifyItems: 'center',
    borderRadius: '50%',
    border: `1px solid ${tokens.colorNeutralStroke2}`,
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
    color: tokens.colorNeutralForeground1,
    fontSize: '17px',
    cursor: 'pointer',
    ':hover': { backgroundColor: brand.bgElev },
    ':disabled': { opacity: 0.4, cursor: 'default' },
  },
  // pílula de busca centralizada, independente do conteúdo lateral
  search: {
    position: 'absolute',
    left: '50%',
    transform: 'translateX(-50%)',
    width: 'min(46vw, 560px)',
    height: '38px',
    display: 'flex',
    alignItems: 'center',
    columnGap: '10px',
    paddingLeft: '16px',
    paddingRight: '16px',
    borderRadius: '20px',
    border: `1px solid ${tokens.colorNeutralStroke2}`,
    backgroundColor: 'rgba(20, 20, 26, 0.72)',
    color: tokens.colorNeutralForeground3,
    cursor: 'text',
    '& input': {
      flexGrow: 1,
      border: 'none',
      backgroundColor: 'transparent',
      color: tokens.colorNeutralForeground1,
      font: 'inherit',
      outlineStyle: 'none',
    },
    '& input::placeholder': { color: tokens.colorNeutralForeground3 },
  },
  clock: {
    color: tokens.colorNeutralForeground3,
    fontVariantNumeric: 'tabular-nums',
    fontSize: tokens.fontSizeBase200,
  },
  scroll: {
    flexGrow: 1,
    overflowY: 'auto',
    paddingTop: '4px',
    paddingLeft: '32px',
    paddingRight: '32px',
    paddingBottom: '100px',
    '::-webkit-scrollbar': { width: '10px' },
    '::-webkit-scrollbar-thumb': {
      backgroundColor: tokens.colorNeutralStroke2,
      borderRadius: '999px',
    },
  },
})

/** Hero grande no topo da Início. */
export const useHeroStyles = makeStyles({
  hero: {
    position: 'relative',
    display: 'block',
    width: '100%',
    height: '264px',
    border: 'none',
    padding: 0,
    borderRadius: brand.radiusLg,
    overflowX: 'hidden',
    overflowY: 'hidden',
    cursor: 'pointer',
    backgroundImage: `linear-gradient(135deg, ${brand.bgElev2}, ${brand.bgElev})`,
    color: 'inherit',
    marginTop: '8px',
    marginBottom: '4px',
    '& img': {
      position: 'absolute',
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
      width: '100%',
      height: '100%',
      objectFit: 'cover',
    },
    '&::after': {
      content: '""',
      position: 'absolute',
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
      backgroundImage:
        'linear-gradient(90deg, rgba(0,0,0,0.78) 0%, rgba(0,0,0,0.15) 55%, transparent 75%), linear-gradient(0deg, rgba(0,0,0,0.5), transparent 40%)',
    },
  },
  body: {
    position: 'absolute',
    left: '28px',
    bottom: '22px',
    zIndex: 1,
    maxWidth: '60%',
    textAlign: 'left',
  },
  kicker: {
    fontSize: tokens.fontSizeBase200,
    fontWeight: 700,
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
    color: brand.accent,
  },
  title: {
    fontSize: 'clamp(20px, 2.4vw, 30px)',
    fontWeight: 800,
    lineHeight: 1.15,
    marginTop: '4px',
    marginBottom: '2px',
  },
  sub: { fontSize: tokens.fontSizeBase200, color: tokens.colorNeutralForeground3 },
})

/** Seções, cabeçalho, toolbar/chips, grade, estado vazio, gerenciar bibliotecas. */
export const useBrowseStyles = makeStyles({
  section: { marginTop: '28px' },
  sectionHead: { display: 'flex', alignItems: 'baseline', columnGap: '8px' },
  sectionTitle: { fontSize: '19px', fontWeight: 700, margin: 0 },
  sectionChevron: {
    color: tokens.colorNeutralForeground3,
    fontSize: '15px',
    border: 'none',
    backgroundColor: 'transparent',
    cursor: 'pointer',
    padding: 0,
  },
  sectionSub: {
    fontSize: tokens.fontSizeBase100,
    color: tokens.colorNeutralForeground3,
    marginTop: '2px',
    marginBottom: '12px',
  },

  grid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(148px, 1fr))',
    rowGap: '18px',
    columnGap: '16px',
    '& > *': { width: 'auto' },
  },

  toolbar: {
    display: 'flex',
    alignItems: 'center',
    columnGap: '10px',
    rowGap: '10px',
    marginTop: '6px',
    marginBottom: '4px',
    flexWrap: 'wrap',
  },
  chip: {
    display: 'inline-flex',
    alignItems: 'center',
    columnGap: '6px',
    height: '32px',
    paddingLeft: '12px',
    paddingRight: '12px',
    borderRadius: '999px',
    border: `1px solid ${tokens.colorNeutralStroke2}`,
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
    color: tokens.colorNeutralForeground1,
    fontSize: tokens.fontSizeBase200,
    cursor: 'pointer',
    ':hover': { backgroundColor: brand.bgElev },
  },
  chipOn: {
    border: `1px solid ${brand.accent}`,
    backgroundColor: brand.accentSoft,
  },
  count: { color: tokens.colorNeutralForeground3, fontSize: tokens.fontSizeBase200 },

  empty: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    rowGap: '10px',
    textAlign: 'center',
    paddingTop: '72px',
    paddingBottom: '72px',
    paddingLeft: '24px',
    paddingRight: '24px',
    color: tokens.colorNeutralForeground3,
    '& h2': { color: tokens.colorNeutralForeground1, fontSize: '18px', margin: 0 },
  },
  emptyIcon: { fontSize: '44px', opacity: 0.5 },

  libManage: {
    marginTop: '14px',
    paddingTop: '12px',
    paddingBottom: '12px',
    paddingLeft: '14px',
    paddingRight: '14px',
    border: `1px solid ${tokens.colorNeutralStroke2}`,
    borderRadius: brand.radius,
    backgroundColor: 'rgba(255, 255, 255, 0.02)',
    maxWidth: '640px',
  },
  libRow: {
    display: 'flex',
    alignItems: 'center',
    columnGap: '12px',
    paddingTop: '8px',
    paddingBottom: '8px',
    borderTop: `1px solid ${tokens.colorNeutralStroke2}`,
    ':first-of-type': { borderTop: 'none' },
  },
  libPath: {
    flexGrow: 1,
    minWidth: 0,
    fontSize: tokens.fontSizeBase100,
    overflowX: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
})

/** Prateleira horizontal (faixas curadas da Início). */
export const useShelfStyles = makeStyles({
  wrap: { position: 'relative' },
  shelf: {
    display: 'flex',
    columnGap: '16px',
    overflowX: 'auto',
    scrollSnapType: 'x proximity',
    scrollbarWidth: 'none',
    paddingBottom: '4px',
    '::-webkit-scrollbar': { display: 'none' },
    '& > *': { scrollSnapAlign: 'start', flexShrink: 0, flexGrow: 0 },
  },
  next: {
    position: 'absolute',
    right: '-8px',
    top: 0,
    bottom: '12px',
    width: '56px',
    display: 'grid',
    alignItems: 'center',
    justifyItems: 'center',
    border: 'none',
    cursor: 'pointer',
    color: tokens.colorNeutralForeground1,
    fontSize: '22px',
    backgroundImage: `linear-gradient(90deg, transparent, ${brand.bg} 70%)`,
    ':hover': { color: brand.accent },
  },
})

/** Cartão-capa em retrato. */
export const useCardStyles = makeStyles({
  card: {
    width: '148px',
    display: 'flex',
    flexDirection: 'column',
    rowGap: '8px',
    border: 'none',
    backgroundColor: 'transparent',
    padding: 0,
    cursor: 'pointer',
    textAlign: 'left',
    color: 'inherit',
    '&:hover [data-art]': { transform: 'translateY(-3px)' },
  },
  art: {
    position: 'relative',
    aspectRatio: '3 / 4',
    borderRadius: brand.radius,
    overflowX: 'hidden',
    overflowY: 'hidden',
    backgroundImage: `linear-gradient(135deg, ${brand.bgElev2}, ${brand.bgElev})`,
    display: 'grid',
    alignItems: 'center',
    justifyItems: 'center',
    transitionProperty: 'transform',
    ...fastTransition,
    '& img': { width: '100%', height: '100%', objectFit: 'cover' },
  },
  badge: {
    position: 'absolute',
    left: '7px',
    bottom: '7px',
    paddingTop: '3px',
    paddingBottom: '3px',
    paddingLeft: '7px',
    paddingRight: '7px',
    borderRadius: '999px',
    fontSize: '10px',
    fontWeight: 700,
    letterSpacing: '0.02em',
    textTransform: 'uppercase',
    backgroundColor: 'rgba(0, 0, 0, 0.62)',
  },
  title: {
    fontSize: tokens.fontSizeBase200,
    fontWeight: 600,
    lineHeight: 1.25,
    overflowX: 'hidden',
    overflowY: 'hidden',
    display: '-webkit-box',
    WebkitLineClamp: 2,
    WebkitBoxOrient: 'vertical',
  },
  sub: { fontSize: tokens.fontSizeBase100, color: tokens.colorNeutralForeground3 },
})

/** Barra de dicas de botão do controle (canto inferior direito). */
export const useHintStyles = makeStyles({
  hints: {
    position: 'fixed',
    right: '22px',
    bottom: '16px',
    display: 'flex',
    columnGap: '16px',
    paddingTop: '8px',
    paddingBottom: '8px',
    paddingLeft: '16px',
    paddingRight: '16px',
    borderRadius: '999px',
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    border: `1px solid ${tokens.colorNeutralStroke2}`,
    fontSize: tokens.fontSizeBase200,
    color: tokens.colorNeutralForeground1,
    zIndex: 50,
    pointerEvents: 'none',
  },
  hint: { display: 'flex', alignItems: 'center', columnGap: '6px' },
  glyph: {
    width: '20px',
    height: '20px',
    borderRadius: '50%',
    display: 'grid',
    alignItems: 'center',
    justifyItems: 'center',
    fontSize: tokens.fontSizeBase100,
    fontWeight: 700,
    color: brand.bg,
  },
  a: { backgroundColor: '#16c60c' },
  b: { backgroundColor: '#e74856' },
  x: { backgroundColor: '#0078d4' },
  y: { backgroundColor: '#fce100' },
  menu: {
    backgroundColor: 'transparent',
    border: `1px solid ${tokens.colorNeutralForeground3}`,
    color: tokens.colorNeutralForeground1,
    fontSize: '11px',
  },
})

/** Página de detalhe do jogo (RomDetail) — estilo "página de jogo" do Xbox:
 *  hero com arte, título grande, botão Jogar, seções em painéis. */
export const useDetailStyles = makeStyles({
  root: {
    display: 'flex',
    flexDirection: 'column',
    rowGap: '20px',
    paddingBottom: '48px',
    maxWidth: '860px',
  },
  back: {
    alignSelf: 'flex-start',
    display: 'inline-flex',
    alignItems: 'center',
    columnGap: '6px',
    height: '32px',
    paddingLeft: '10px',
    paddingRight: '14px',
    borderRadius: '999px',
    border: `1px solid ${tokens.colorNeutralStroke2}`,
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
    color: tokens.colorNeutralForeground1,
    fontSize: tokens.fontSizeBase200,
    cursor: 'pointer',
    ':hover': { backgroundColor: brand.bgElev },
  },
  hero: {
    position: 'relative',
    minHeight: '280px',
    borderRadius: brand.radiusLg,
    overflowX: 'hidden',
    overflowY: 'hidden',
    display: 'flex',
    alignItems: 'flex-end',
    backgroundImage: `linear-gradient(135deg, ${brand.bgElev2}, ${brand.bgElev})`,
  },
  heroArt: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    width: '100%',
    height: '100%',
    objectFit: 'cover',
  },
  heroScrim: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    backgroundImage:
      'linear-gradient(90deg, rgba(0,0,0,0.82) 0%, rgba(0,0,0,0.35) 55%, rgba(0,0,0,0.1) 100%), linear-gradient(0deg, rgba(0,0,0,0.7), transparent 55%)',
  },
  heroBody: { position: 'relative', zIndex: 1, padding: '26px', maxWidth: '72%' },
  title: {
    fontSize: 'clamp(24px, 3vw, 40px)',
    fontWeight: 800,
    lineHeight: 1.1,
    margin: 0,
  },
  badges: { display: 'flex', columnGap: '8px', rowGap: '6px', marginTop: '10px', flexWrap: 'wrap' },
  badge: {
    paddingTop: '3px',
    paddingBottom: '3px',
    paddingLeft: '10px',
    paddingRight: '10px',
    borderRadius: '999px',
    fontSize: tokens.fontSizeBase200,
    fontWeight: 600,
    textTransform: 'uppercase',
    letterSpacing: '0.02em',
    backgroundColor: 'rgba(0, 0, 0, 0.55)',
    border: `1px solid ${tokens.colorNeutralStroke2}`,
  },
  desc: {
    marginTop: '12px',
    fontSize: tokens.fontSizeBase300,
    lineHeight: 1.5,
    color: tokens.colorNeutralForeground2,
    display: '-webkit-box',
    WebkitLineClamp: 4,
    WebkitBoxOrient: 'vertical',
    overflowX: 'hidden',
    overflowY: 'hidden',
  },
  path: { marginTop: '10px', fontSize: tokens.fontSizeBase100, color: tokens.colorNeutralForeground3 },
  actions: { display: 'flex', columnGap: '12px', rowGap: '10px', alignItems: 'end', flexWrap: 'wrap' },
  section: { display: 'flex', flexDirection: 'column', rowGap: '10px' },
  sectionTitle: { fontSize: '16px', fontWeight: 700, margin: 0 },
  panel: {
    display: 'flex',
    flexDirection: 'column',
    rowGap: '12px',
    paddingTop: '14px',
    paddingBottom: '14px',
    paddingLeft: '16px',
    paddingRight: '16px',
    borderRadius: brand.radius,
    border: `1px solid ${tokens.colorNeutralStroke2}`,
    backgroundColor: 'rgba(255, 255, 255, 0.02)',
    maxWidth: '560px',
  },
  field: { display: 'flex', flexDirection: 'column', rowGap: '4px' },
  stateRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    columnGap: '10px',
    paddingTop: '8px',
    paddingBottom: '8px',
    paddingLeft: '12px',
    paddingRight: '12px',
    borderRadius: brand.radius,
    backgroundColor: brand.bgElev,
  },
  hint: { fontSize: tokens.fontSizeBase100, color: tokens.colorNeutralForeground3 },
})

/** Menu de pausa da PlayScreen (fora do `.xb-app`, então tem seu próprio
 *  anel de foco pra navegação por controle). */
export const usePauseStyles = makeStyles({
  scrim: {
    position: 'fixed',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.62)',
    display: 'grid',
    alignItems: 'center',
    justifyItems: 'center',
    zIndex: 100,
    '& button:focus, & a:focus': {
      outlineWidth: '3px',
      outlineStyle: 'solid',
      outlineColor: tokens.colorNeutralForeground1,
      outlineOffset: '2px',
      borderRadius: brand.radius,
    },
  },
  panel: {
    display: 'flex',
    flexDirection: 'column',
    rowGap: '8px',
    minWidth: '280px',
    paddingTop: '22px',
    paddingBottom: '22px',
    paddingLeft: '22px',
    paddingRight: '22px',
    borderRadius: brand.radiusLg,
    backgroundColor: '#14141a',
    border: `1px solid ${tokens.colorNeutralStroke2}`,
    color: tokens.colorNeutralForeground1,
  },
  title: { fontSize: '18px', fontWeight: 700, margin: '0 0 6px' },
  states: {
    display: 'flex',
    flexDirection: 'column',
    rowGap: '4px',
    maxHeight: '220px',
    overflowY: 'auto',
    marginTop: '2px',
    marginBottom: '2px',
  },
  stateRow: {
    display: 'flex',
    alignItems: 'center',
    columnGap: '10px',
    padding: '6px',
    borderRadius: brand.radius,
    border: `1px solid ${tokens.colorNeutralStroke2}`,
    backgroundColor: 'rgba(255,255,255,0.03)',
    color: tokens.colorNeutralForeground1,
    cursor: 'pointer',
    textAlign: 'left',
    font: 'inherit',
    ':hover': { backgroundColor: brand.bgElev },
  },
  stateLabel: { fontSize: tokens.fontSizeBase200, lineHeight: 1.3, minWidth: 0 },
  stateDate: { fontSize: tokens.fontSizeBase100, color: tokens.colorNeutralForeground3 },
})
