[package]
name = "core-ipc"
version.workspace = true
edition.workspace = true

[dependencies]
serde = { workspace = true }
domain = { path = "../domain" }
bincode = { version = "2", features = ["serde"] }

[target.'cfg(unix)'.dependencies]
rustix = { version = "1", features = ["net", "fs", "mm", "process", "std"] }

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61", features = [
    "Win32_Foundation",
    "Win32_Security",
    "Win32_Storage_FileSystem",
    "Win32_System_IO",
    "Win32_System_Pipes",
    "Win32_System_Memory",
] }
